Update README.md
`cask` as a parameter no longer works in recent versions and gives the following output:

```➜  ~ brew cask install pharo-project/pharo/pharo-launcher
Error: Unknown command: cask```

I also removed parts of the note, as there doesn’t seem to be any formula with “pharo” in its name anymore.